ProVictor/Algorithm-Library

primal_dual/primal_dual.py
primal_dual/simplex2.py

Closes https://github.com/ProVictor/Algorithm-Library/issues/3
Fixes #
- 
- 
- 
- 
Thanks!

Added primal dual algorithm 

---

Simplex-Algorithm/simplex.py

Fixes #
- #1  
- Python
Thanks!

Simplex Algorithm

---

Huffman Coding/Huffman_Coding.cpp

Huffman Coding STL implementation

---

Circular Linked List/Circular_Linked_List.c

Circular Linked List Basics

---

LongestPallindrome/PallindromeStromg.cpp
ReverseDecode/reverseNDecode.c

Reverse decode

---

LongestPallindrome/PallindromeStromg.cpp

Adding the Longest Pallindrome Finder

---

djikstra/Djiskstra.cpp

Djikstra Added

---

ThreeSum/ThreeSum.cpp

3Sum Added

---

Lucas_Theorem/Lucas_Theorem.java

Lucas Theorem

---

Longest_Repeating_Subsequence/Longest_Repeating_Subsequence.cpp
Lucas_Theorem/Lucas_Theorem.java

Longest repeating subsequence

---

Sparse_Table/Sparse_Table.java

Sparse Table

---

Bit_Manipulation/countSetBits.cpp
Bit_Manipulation/flippingBits.cpp
Bit_Manipulation/invertBits.cpp
Bit_Manipulation/magicNumber.cpp

Count sets

---

Bit_Manipulation/flippingBits.cpp

Flipping of Bits in C++

---

Bit_Manipulation/flippingBits.cpp
Bit_Manipulation/invertBits.cpp

Invert bit

---

LinkedListCycleDetect/detect_cycle_linked_list.py

Linked List Cycle Detection Algorithm Added in Python

---

Tree/tree.py

Added tree creation with all methods in python

---

LinkedList/singly_linked_list.py

Singly Linked List in Python Added

---

kmp/kmp.cpp

Kmp string algorithm

---

miller_rabin/miller_rabin.cpp

Miller rabin code added

---

pollard_rho/pollard_rho.cpp

Pollard rho algorithm

---

pollard_rho/pollard_rho.cpp
rabin_karp/rabin_karp.cpp

Rabin karp
